// utils/mail.js
import nodemailer from "nodemailer";

// Setup the Outlook transporter
const transporter = nodemailer.createTransport({
  host: "smtp.office365.com", // For Outlook
  port: 587,
  secure: false,
  auth: {
    user: "info@naturevalley.com.pk",
    pass: "fljrbflytxfgwkln", // App password
  },
});

export const sendWelcomeEmail = async (toEmail) => {
  if (!toEmail || !toEmail.includes("@")) {
    console.error("❌ Invalid email address:", toEmail);
    return;
  }

  const mailOptions = {
    from: '"Nature Valley" <info@naturevalley.com.pk>',
    to: toEmail,
    subject: "Welcome to Nature Valley 🌿",
    html: `
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>New email template 2025-04-11</title> <!--[if (mso 16)]><style type="text/css"> a {text-decoration: none;}  </style><![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><!--[if !mso]><!-- --><link href="https://fonts.googleapis.com/css2?family=Spartan:wght@300&display=swap" rel="stylesheet"><!--<![endif]--><!--[if mso]><xml> <w:WordDocument xmlns:w="urn:schemas-microsoft-com:office:word"> <w:DontUseAdvancedTypographyReadingMail/> </w:WordDocument> </xml>
<![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;}@media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-m-p20b { padding-bottom:20px!important }
 .es-p-default { } *[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:30px!important; text-align:left } h2 { font-size:24px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:24px!important }
 .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:14px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:18px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class="body" style="width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="en" style="background-color:#BDD7D6"><!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#BDD7D6" origin="0.5, 0" position="0.5, 0"></v:fill> </v:background><![endif]--><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#BDD7D6"><tr>
<td valign="top" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="es-header" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="es-header-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px" role="none"><tr>
<td align="left" background="https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/union_zlc.png" bgcolor="#EFF2DD" style="Margin:0;padding-top:5px;padding-right:20px;padding-bottom:5px;padding-left:20px;background-image:url(https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/union_zlc.png);background-repeat:no-repeat;background-position:center top;border-radius:20px 20px 0px 0px;background-color:#eff2dd"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:560px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0"><p style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:21px;letter-spacing:0;color:#516365;font-size:14px"><a target="_blank" href="https://viewstripo.email" style="mso-line-height-rule:exactly;text-decoration:none;color:#516365;font-size:14px">Welcome</a></p> </td></tr></table></td></tr></table></td></tr> <tr><td align="left" bgcolor="#EFF2DD" style="Margin:0;padding-right:20px;padding-left:20px;padding-top:30px;padding-bottom:15px;background-color:#eff2dd"><table cellspacing="0" cellpadding="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" class="es-m-p0r" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://viewstripo.email" style="mso-line-height-rule:exactly;text-decoration:underline;color:#516365;font-size:14px"><img src="https://ftjvftc.stripocdn.email/content/guids/eb10ea03-444b-4a9b-904b-c2846a5dff16/images/asset_23x.png" alt="Logo" width="200" title="Logo" class="adapt-img" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellspacing="0" cellpadding="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr><td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" bgcolor="#EFF2DD" align="center" class="es-content-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#EFF2DD;width:600px"><tr><td align="left" style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:600px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0"><img src="https://ftjvftc.stripocdn.email/content/guids/eb10ea03-444b-4a9b-904b-c2846a5dff16/images/screenshot_20250410_225051.png" alt="" width="600" class="adapt-img" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table></td></tr><tr><td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-top:30px;padding-bottom:40px"><table width="100%" cellspacing="0" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" class="es-m-p0r es-m-p20b" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;padding-bottom:20px"><h1 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:34px;font-style:normal;font-weight:bold;line-height:40.8px;color:#516365">Welcome to <strong>Nature Valley</strong> !</h1> <h1 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:34px;font-style:normal;font-weight:bold;line-height:40.8px;color:#516365">we're excited to have you in our green family! 🌿</h1></td></tr><tr>
<td align="left" style="padding:0;Margin:0;padding-top:5px;padding-bottom:25px;font-size:0px"><img src="https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/rectangle_5385.png" alt="" width="50" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></td></tr> <tr>
<td align="left" style="padding:0;Margin:0;padding-bottom:30px"><h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#516365">With 23 years of experience in the nursery and landscaping industry, Nature Valley is your trusted partner for creating and maintaining beautiful green spaces. We specialize in providing comprehensive landscaping services to societies, offices, homes, and green belts, ensuring that every project reflects our commitment to quality and sustainability.</h3></td></tr> <tr>
<td align="left" style="padding:0;Margin:0"><!--[if mso]><a href="https://naturevalley.com.pk/contact" target="_blank" hidden> <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" esdevVmlButton href="https://naturevalley.com.pk/contact" style="height:46px; v-text-anchor:middle; width:163px" arcsize="26%" stroke="f" fillcolor="#0b3d2c"> <w:anchorlock></w:anchorlock> <center style='color:#ffffff; font-family:Spartan, sans-serif; font-size:16px; font-weight:700; line-height:16px; mso-text-raise:1px'>Contact Us </center> </v:roundrect></a>
<![endif]--><!--[if !mso]><!-- --><span class="es-button-border msohide" style="border-style:solid;border-color:#2CB543;background:#0B3D2C;border-width:0px;display:inline-block;border-radius:12px;width:auto;mso-hide:all"><a href="https://naturevalley.com.pk/contact" target="_blank" class="es-button" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:18px;padding:15px 30px 10px 30px;display:inline-block;background:#0B3D2C;border-radius:12px;font-family:Spartan, sans-serif;font-weight:bold;font-style:normal;line-height:21.6px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #0B3D2C">Contact Us </a> </span><!--<![endif]--></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding="0" cellspacing="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr><td align="center" style="padding:0;Margin:0"><table bgcolor="#0B3D2C" align="center" cellpadding="0" cellspacing="0" class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#0B3D2C;width:600px" role="none"><tr><td align="left" style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:600px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0px"><img src="https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/subtract.png" alt="" width="600" class="adapt-img" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-right:20px;padding-left:20px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:560px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;padding-bottom:20px;padding-top:20px"><h1 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:34px;font-style:normal;font-weight:bold;line-height:40.8px;color:#eff2dd">​What We Offer at Nature Valley</h1></td></tr></table></td></tr></table></td></tr> <tr><td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-top:30px;padding-bottom:30px"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr>
<td style="width:260px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="center" valign="top" class="es-m-p20b" style="padding:0;Margin:0;width:260px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" style="padding:0;Margin:0;padding-top:20px;padding-bottom:10px"><h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a target="_blank" href="https://viewstripo.email" class="b_title" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"> 🌳 <strong>Landscaping Solutions</strong> &nbsp;</a></h3> </td></tr><tr><td align="left" style="padding:0;Margin:0;padding-bottom:10px;padding-top:10px"><p class="b_description" style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:24px;letter-spacing:0;color:#ffffff;font-size:16px">Customized designs for homes, offices, societies &amp; green belts</p></td></tr></table></td></tr></table> <!--[if mso]></td><td style="width:40px"></td>
<td style="width:260px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr><td align="center" valign="top" style="padding:0;Margin:0;width:260px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;padding-top:20px;padding-bottom:10px"><h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a target="_blank" href="https://viewstripo.email" class="b_title" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"> 🪴 <strong>Plant Nursery</strong></a></h3>
 <h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a href="https://viewstripo.email" target="_blank" class="b_title" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"><strong><br></strong> </a></h3></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-bottom:10px;padding-top:10px"><p class="b_description" style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:24px;letter-spacing:0;color:#ffffff;font-size:16px">A wide variety of healthy plants delivered to your doorstep</p></td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr> <tr>
<td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-bottom:40px;padding-top:20px"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr><td style="width:260px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="center" valign="top" class="es-m-p20b" style="padding:0;Margin:0;width:260px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" style="padding:0;Margin:0;padding-top:20px;padding-bottom:10px"><h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a target="_blank" href="https://viewstripo.email" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"> 🌼 <strong>Maintenance Services</strong> </a></h3> </td></tr><tr><td align="left" style="padding:0;Margin:0;padding-bottom:10px;padding-top:10px"><p style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:24px;letter-spacing:0;color:#ffffff;font-size:16px">Regular care to keep your green spaces thriving</p></td></tr></table></td></tr></table> <!--[if mso]></td><td style="width:40px"></td>
<td style="width:260px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr><td align="center" valign="top" style="padding:0;Margin:0;width:260px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;padding-top:20px;padding-bottom:10px"><h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a target="_blank" href="https://viewstripo.email" class="b_title" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"> 🌿 <strong>Sustainable Practices</strong></a></h3>
 <h3 style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:bold;line-height:24px;color:#eff2dd"><a href="https://viewstripo.email" target="_blank" class="b_title" style="mso-line-height-rule:exactly;text-decoration:none;color:#eff2dd;font-size:20px"><strong><br></strong> </a></h3></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-bottom:10px;padding-top:10px"><p class="b_description" style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:24px;letter-spacing:0;color:#ffffff;font-size:16px">Eco-friendly solutions rooted in 23 years of experience</p></td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr> <tr>
<td align="left" style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" valign="top" style="padding:0;Margin:0;width:600px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0px"><img src="https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/subtract_xHj.png" alt="" width="600" class="adapt-img" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding="0" cellspacing="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr><td align="center" style="padding:0;Margin:0"><table bgcolor="#ffffff" align="center" cellpadding="0" cellspacing="0" class="es-content-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#EFF2DD;width:600px"><tr><td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-top:30px;padding-bottom:20px"><table width="100%" cellspacing="0" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" class="es-m-p0r es-m-p20b" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;padding-bottom:20px"><h1 class="es-m-txt-c" style="Margin:0;font-family:Spartan, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:34px;font-style:normal;font-weight:bold;line-height:40.8px;color:#516365">Let's start this journey together!</h1> </td></tr><tr><td align="center" style="padding:0;Margin:0;padding-top:5px;padding-bottom:25px;font-size:0px"><img src="https://ftjvftc.stripocdn.email/content/guids/CABINET_55133f7da1d530766fabffa3c07ab1852570caf3acae85e9fef2735054562cd4/images/rectangle_5385.png" alt="" width="50" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></td></tr>
<tr><td align="center" style="padding:0;Margin:0"><p style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:27px;letter-spacing:0;color:#516365;font-size:18px">Best Wishes,</p></td></tr></table></td></tr></table></td></tr> <tr><td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-bottom:30px;padding-top:20px"><!--[if mso]><table style="width:560px" cellpadding="0" cellspacing="0"><tr><td style="width:270px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" class="es-m-p20b" style="padding:0;Margin:0;width:270px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="right" class="es-m-txt-c" style="padding:0;Margin:0"><!--[if mso]><a href="https://naturevalley.com.pk/contact" target="_blank" hidden> <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" esdevVmlButton href="https://naturevalley.com.pk/contact" style="height:46px; v-text-anchor:middle; width:209px" arcsize="30%" strokecolor="#0b3d2c" strokeweight="1px" fillcolor="#eff2dd"> <w:anchorlock></w:anchorlock> <center style='color:#0b3d2c; font-family:Spartan, sans-serif; font-size:16px; font-weight:700; line-height:16px; mso-text-raise:1px'>Contact Us ></center> </v:roundrect></a>
<![endif]--><!--[if !mso]><!-- --><span class="es-button-border msohide" style="border-style:solid;border-color:#0b3d2c;background:#eff2dd;border-width:2px;display:inline-block;border-radius:14px;width:auto;mso-hide:all"><a href="https://naturevalley.com.pk/contact" target="_blank" class="es-button" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#0b3d2c;font-size:18px;padding:15px 40px 10px 45px;display:inline-block;background:#eff2dd;border-radius:14px;font-family:Spartan, sans-serif;font-weight:bold;font-style:normal;line-height:21.6px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #EFF2DD">Contact Us &gt;</a> </span><!--<![endif]--></td></tr></table></td></tr></table> <!--[if mso]></td><td style="width:20px"></td>
<td style="width:270px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr><td align="left" style="padding:0;Margin:0;width:270px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" class="es-m-txt-c" style="padding:0;Margin:0"><!--[if mso]><a href="https://wa.me/message/THEOF7NTVZ63N1" target="_blank" hidden> <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" esdevVmlButton href="https://wa.me/message/THEOF7NTVZ63N1" style="height:46px; v-text-anchor:middle; width:202px" arcsize="26%" strokecolor="#ee6b61" strokeweight="1px" fillcolor="#0b3d2c"> <w:anchorlock></w:anchorlock> <center style='color:#ffffff; font-family:Spartan, sans-serif; font-size:16px; font-weight:700; line-height:16px; mso-text-raise:1px'>Say Hi ></center> </v:roundrect></a>
<![endif]--><!--[if !mso]><!-- --><span class="es-button-border msohide" style="border-style:solid;border-color:#ee6b61;background:#0b3d2c;border-width:2px;display:inline-block;border-radius:12px;width:auto;mso-hide:all"><a href="https://wa.me/message/THEOF7NTVZ63N1" target="_blank" class="es-button es-button-1684935065829" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:18px;padding:15px 60px 10px;display:inline-block;background:#0b3d2c;border-radius:12px;font-family:Spartan, sans-serif;font-weight:bold;font-style:normal;line-height:21.6px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #0b3d2c">Say Hi &gt;</a> </span><!--<![endif]--></td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></td></tr></table>
 <table cellpadding="0" cellspacing="0" align="center" class="es-footer" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top"><tr><td align="center" style="padding:0;Margin:0"><table bgcolor="#3c2c4c" align="center" cellpadding="0" cellspacing="0" class="es-footer-body" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#EFF2DD;width:600px"><tr><td align="left" style="Margin:0;padding-right:20px;padding-left:20px;padding-bottom:20px;padding-top:40px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="left" style="padding:0;Margin:0;width:560px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" width="100%" class="es-menu" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr class="links"><td align="center" valign="top" width="25%" style="Margin:0;border:0;padding-bottom:10px;padding-top:10px;padding-right:5px;padding-left:5px"><div style="vertical-align:middle;display:block"><a target="_blank" href="https://naturevalley.com.pk" style="mso-line-height-rule:exactly;text-decoration:none;font-family:Spartan, sans-serif;display:block;color:#516365;font-size:14px">About us</a> </div></td>
<td align="center" valign="top" width="25%" style="Margin:0;border:0;padding-bottom:10px;padding-top:10px;padding-right:5px;padding-left:5px"><div style="vertical-align:middle;display:block"><a target="_blank" href="https://naturevalley.com.pk/blogs" style="mso-line-height-rule:exactly;text-decoration:none;font-family:Spartan, sans-serif;display:block;color:#516365;font-size:14px">Blogs</a></div></td><td align="center" valign="top" width="25%" style="Margin:0;border:0;padding-bottom:10px;padding-top:10px;padding-right:5px;padding-left:5px"><div style="vertical-align:middle;display:block"><a target="_blank" href="https://naturevalley.com.pk/team" style="mso-line-height-rule:exactly;text-decoration:none;font-family:Spartan, sans-serif;display:block;color:#516365;font-size:14px">Our Team</a></div></td>
 <td align="center" valign="top" width="25%" style="Margin:0;border:0;padding-bottom:10px;padding-top:10px;padding-right:5px;padding-left:5px"><div style="vertical-align:middle;display:block"><a target="_blank" href="https://naturevalley.com.pk/contact" style="mso-line-height-rule:exactly;text-decoration:none;font-family:Spartan, sans-serif;display:block;color:#516365;font-size:14px">Contact Us </a></div></td></tr></table></td></tr> <tr><td align="center" style="padding:0;Margin:0;padding-bottom:20px;padding-top:20px;font-size:0"><table cellpadding="0" cellspacing="0" class="es-table-not-adapt es-social" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;padding-right:20px"><a target="_blank" href="https://www.facebook.com/profile.php?id=61565466936339&mibextid=LQQJ4d" style="mso-line-height-rule:exactly;text-decoration:underline;color:#516365;font-size:14px"><img title="Facebook" src="https://ftjvftc.stripocdn.email/content/assets/img/social-icons/logo-colored-bordered/facebook-logo-colored-bordered.png" alt="Fb" width="24" height="24" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0;padding-right:20px"><a target="_blank" href="https://www.instagram.com/naturevalley.pk/" style="mso-line-height-rule:exactly;text-decoration:underline;color:#516365;font-size:14px"><img title="Instagram" src="https://ftjvftc.stripocdn.email/content/assets/img/social-icons/logo-colored-bordered/instagram-logo-colored-bordered.png" alt="Inst" width="24" height="24" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0"><a target="_blank" href="https://www.linkedin.com/company/naturevalley/" style="mso-line-height-rule:exactly;text-decoration:underline;color:#516365;font-size:14px"><img title="LinkedIn" src="https://ftjvftc.stripocdn.email/content/assets/img/social-icons/logo-colored-bordered/linkedin-logo-colored-bordered.png" alt="In" width="24" height="24" style="display:block;font-size:18px;border:0;outline:none;text-decoration:none"></a></td></tr></table></td></tr> <tr>
<td align="center" style="padding:0;Margin:0;padding-top:10px"><p style="Margin:0;mso-line-height-rule:exactly;font-family:Spartan, sans-serif;line-height:21px;letter-spacing:0;color:#516365;font-size:14px">You are receiving this email because you have visited our site or asked us about the regular newsletter. Make sure our messages get to your Inbox (and not your bulk or junk folders).<br><strong><a target="_blank" href="https://viewstripo.email" style="mso-line-height-rule:exactly;text-decoration:none;color:#516365;font-size:14px">Privacy police</a> | <a target="_blank" style="mso-line-height-rule:exactly;text-decoration:none;color:#516365;font-size:14px" href="">Unsubscribe</a></strong></p></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding="0" cellspacing="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"></table></td></tr></table></div></body></html>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Welcome email sent to ${toEmail}: ${info.messageId}`);
  } catch (error) {
    console.error(`❌ Failed to send email to ${toEmail}`, error);
  }
};

